### ISSUE TITLE
AutoConnect

### ISSUE THREAD

**Issue by Kanbach** [Kanbach/ESP8266#1]
Hi,

I get the following compilation error if I use an example sketch for AutoConnect by Hieronom:

https://github.com/Hieromon/AutoConnect/tree/master/examples

**Users/Kanbach/Documents/Arduino/libraries/AutoConnect/src/AutoConnectUpdate.cpp:92:162: error: 'UpdateVariedClass::THandlerFunction_Progress' has not been declared**

Arduino: 1.8.10 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

used libs:

Bibliothek ESP8266WiFi in Version 1.0 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/ESP8266WiFi  wird verwendet
Bibliothek ESP8266WebServer in Version 1.0 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/ESP8266WebServer  wird verwendet
Bibliothek ArduinoOTA in Version 1.0 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/ArduinoOTA  wird verwendet
Bibliothek AutoConnect in Version 1.1.3 im Ordner: /Users/Kanbach/Documents/Arduino/libraries/AutoConnect  wird verwendet
Bibliothek DNSServer in Version 1.1.1 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/DNSServer  wird verwendet
Bibliothek EEPROM in Version 1.0 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/EEPROM  wird verwendet
Bibliothek PageBuilder in Version 1.3.7 im Ordner: /Users/Kanbach/Documents/Arduino/libraries/PageBuilder  wird verwendet
Bibliothek ArduinoJson in Version 6.14.0 im Ordner: /Users/Kanbach/Documents/Arduino/libraries/ArduinoJson  wird verwendet
Bibliothek Ticker in Version 1.0 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/Ticker  wird verwendet
Bibliothek ESP8266HTTPClient in Version 1.2 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/ESP8266HTTPClient  wird verwendet
Bibliothek ESP8266httpUpdate in Version 1.3 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/ESP8266httpUpdate  wird verwendet
Bibliothek ESP8266mDNS in Version 1.2 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/ESP8266mDNS  wird verwendet
Bibliothek SPI in Version 1.0 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/SPI  wird verwendet
Bibliothek SD in Version 1.0.5 im Ordner: /Users/Kanbach/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.0/libraries/SD  wird verwendet

Any comments are welcome...

**Comment by tranquangvu0651** [comment]
Hi @Kanbach, I have same issue and you just update UPDATE PLATFORM of ESP8266.

**Comment by Kanbach** [comment]
Hi,
thanks for the answer, it helps.

BR
Andreas
